server:
  port: 2222

spring:
  application:
    name: gatewayserver
# get all configs from eureka server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          # lowerCaseServiceId: true

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/