server:
  port: 2222

spring:
  application:
    name: gatewayserver
# get all configs from eureka server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          # lowerCaseServiceId: true
      # enable routing
#      getting cors error for post request
#      routes:
#        - id: authservice
#          uri: lb://AUTHSERVICE
#          predicates:
#            - Path=/API_GATEWAY/authservice/**
#            - Method=GET
#          filters:
#            # need to replace our prefix
#            - RewritePath=/API_GATEWAY/authservice/(?<segment>.*), /${segment}
#        - id: reposervice
#          uri: lb://REPOSERVICE
#          predicates:
#            - Path=/API_GATEWAY/reposervice/**
#            - Method=GET,POST
#          filters:
#            - RewritePath=/API_GATEWAY/reposervice/(?<segment>.*), /${segment}
      # cors config
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
            allowedHeaders: "*"

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/