server:
  port: 8080

spring:
  application:
    name: authservice
  datasource:
    url: jdbc:mysql://localhost:3306/apprepo?useSSL=false&serverTimezone=UTC
    username: root
    password: my-secret-pw
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

logging:
  level:
    com:
      syed:
        authservice: DEBUG
  file:
    name: authservice.log

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

github:
  clientId: e7913495da0b920cfa5c
  clientSecret: a1dd477837c5a518f1c756cf53601e41840a9419
