server:
  port: 8081

spring:
  application:
    name: reposervice
  datasource:
    url: jdbc:mysql://localhost:3306/repo?useSSL=false&serverTimezone=UTC
    username: root
    password: my-secret-pw
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/