server:
  port: 8081

spring:
  application:
    name: reposervice
  datasource:
    url: jdbc:mysql://localhost:3306/apprepo?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: mysql123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  profiles:
    active: dev
  # springfox-boot-starter crashing server
  # https://stackoverflow.com/questions/40241843/failed-to-start-bean-documentationpluginsbootstrapper-in-spring-data-rest
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

pom:
  version: @project.version@