version: "3"

services:
  mysql-service:
    image: app-repo/mysql_db:latest
    build: ./mysql
    container_name: mysql-service
    ports:
      - 3306:3306
    restart: always

  eureka-server:
    image: app-repo/eureka-server:latest
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - 8761:8761
    restart: always

  gateway-server:
    image: app-repo/gateway-server:latest
    build: ./gateway-server
    container_name: gateway-server
    ports:
      - 2222:2222
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "${EUREKA_ENDPOINT}"
    depends_on:
      - eureka-server
    restart: always

  auth-service:
    image: app-repo/auth-service:latest
    build: ./auth-service
    container_name: auth-service
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: "${DATABASE_URL}"
      SPRING_DATASOURCE_PASSWORD: "${DATABASE_PASSWORD}"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "${EUREKA_ENDPOINT}"
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      - mysql-service
      - eureka-server
      - gateway-server
    restart: always

  repo-service:
    image: app-repo/repo-service:latest
    build: ./repo-service
    container_name: repo-service
    ports:
      - 8081:8081
    environment:
      SPRING_DATASOURCE_URL: "${DATABASE_URL}"
      SPRING_DATASOURCE_PASSWORD: "${DATABASE_PASSWORD}"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "${EUREKA_ENDPOINT}"
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      - mysql-service
      - eureka-server
      - gateway-server
    restart: always

  feedback-service:
    image: app-repo/feedback-service:latest
    build: ./feedback-service
    container_name: feedback-service
    ports:
      - 8082:8082
    environment:
      SPRING_DATASOURCE_URL: "${DATABASE_URL}"
      SPRING_DATASOURCE_PASSWORD: "${DATABASE_PASSWORD}"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "${EUREKA_ENDPOINT}"
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      - mysql-service
      - eureka-server
      - gateway-server
    restart: always

  client-app:
    image: app-repo/client-react-app
    build: ./client
    container_name: client-app
    ports:
      - 3000:3000
    # environment:
      # VITE_SOME_KEY: hello world
    restart: always
