version: "3"

services:
  mysql-service:
    image: app-repo/mysql_db:latest
    build: ./mysql
    ports:
      - 3306:3306
    restart: always

  eureka-server:
    image: app-repo/eureka-server:latest
    build: ./eureka-server
    ports:
      - 8761:8761
    restart: always

  gateway-server:
    image: app-repo/gateway-server:latest
    build: ./gateway-server
    ports:
      - 2222:2222
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
    restart: always

  auth-service:
    image: app-repo/auth-service:latest
    build: ./auth-service
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-service:3306/apprepo?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      # was causing alot of errors and taking a long time to connect to db - so added allowPublicKeyRetrieval=true
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      - mysql-service
      - eureka-server
      - gateway-server
    restart: always

  client-app:
    image: app-repo/client-react-app
    build: ./client
    ports:
      - 3000:3000
    environment:
      VITE_SOME_KEY: hello world
    restart: always
