server:
  port: 8082

spring:
  application:
    name: feedbackservice
  datasource:
    url: jdbc:mysql://localhost:3306/apprepo?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: mysql123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  profiles:
    active: dev

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

pom:
  version: @project.version@