logging:
  level:
#    org:
#      hibernate:
#        SQL: DEBUG
#        type:
#          descriptor:
#            sql:
#              BasicBinder: TRACE
    com:
      syed:
        feedbackservice: DEBUG